# Generated by Django 4.0.2 on 2023-06-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='uniqueId',
        ),
    ]
