# Generated by Django 4.0.2 on 2023-06-07 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_chatsession_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='business_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='business_type',
            field=models.CharField(blank=True, choices=[('Private', 'Private'), ('Partnership', 'Partnership'), ('Non-Profit', 'Non-Profit')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='product_service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='progress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='years',
            field=models.TextField(blank=True, null=True),
        ),
    ]
