# Generated by Django 4.0.2 on 2023-08-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storechatbot', '0004_apartment_chatsession_profiles_propertymanager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
    ]
