# Generated by Django 4.0.2 on 2023-09-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storechatbot', '0005_rename_phone_number_profiles_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renterpayment',
            name='renter',
        ),
        migrations.RemoveField(
            model_name='renterpayment',
            name='transaction_code',
        ),
        migrations.RemoveField(
            model_name='repairrequest',
            name='renter',
        ),
        migrations.AddField(
            model_name='apartment',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storechatbot.profiles'),
        ),
        migrations.AddField(
            model_name='renterpayment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storechatbot.transaction'),
        ),
        migrations.DeleteModel(
            name='Renter',
        ),
    ]
