# Generated by Django 4.0.2 on 2023-09-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storechatbot', '0008_delete_message_delete_propertymanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='question_no',
            field=models.IntegerField(default=0),
        ),
    ]
