# Generated by Django 4.0.2 on 2023-09-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storechatbot', '0018_alter_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renterpayment',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='repairrequest',
            name='apartment',
        ),
        migrations.AddField(
            model_name='renterpayment',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storechatbot.profiles'),
        ),
        migrations.AddField(
            model_name='repairrequest',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storechatbot.profiles'),
        ),
    ]
