# Generated by Django 4.0.2 on 2023-09-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storechatbot', '0019_remove_renterpayment_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue'), ('VeryLate', 'VeryLate')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='payment_regularity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='RenterPayment',
        ),
    ]
